name: Send PR Data To LISA
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
  Send-PR-To-LISA:
    runs-on: windows-latest
    steps:
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "14.x"

      - name: Checkout Code
        uses: actions/checkout@v2
        continue-on-error: false
      
      - run: dir
      - run: cd PullRequestDataFetch
      - run: dir
      
      - run: echo "GITHUB_HEAD_REF = ${{github.head_ref}} / GITHUB_REF = ${{github.ref}}"

