name: Send PR Data To LISA
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
  Send-PR-To-LISA:
    runs-on: windows-latest
    steps:
      - run: echo "GITHUB_HEAD_REF = ${{github.head_ref}} / GITHUB_REF = ${{github.ref}}"
      - run: node C:node_apps\\index.js fetch-pr-data id=4 repo=${{github.repository}}

